import type { Metadata } from "next";
import { Poppins, Poly } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: '--font-poppins'
});

const poly = Poly({
  weight: ['400'],
  subsets: ["latin"],
  variable: '--font-poly'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poly.variable}`}>
        {children}    
      </body>
    </html>
  );
}
